//
//  SwaggerMethod.swift
//  Ernie
//
//  Created by Randy Haid on 12/7/17.
//  Copyright © 2017 Randy Haid. All rights reserved.
//

import Foundation

class SwaggerMethod
{
    enum SwaggerDataType
    {
        case Integer, String, Boolean, Array, Object
    }
    
    enum SwaggerMethodType
    {
        case GET, POST, PUT, EVENT
    }
    
    class SwaggerMethodArgument
    {
        var argumentName: String
        var argumentType: SwaggerDataType
        var isArgumentRequired = false
        var argumentDescription: String?
        init(name: String, type: SwaggerDataType)
        {
            self.argumentName = name
            self.argumentType = type
        }
    }
    
    class SwaggerResponse
    {
        var responseHttpCode: Int = 200
        var responseDataType = SwaggerDataType.Boolean
        var responseDescription: String?
    }
    
    /// The name of the method.
    var methodName: String
    
    /// Indicates what kind of method this is in the HTTP world.
    var methodType = SwaggerMethodType.GET
    
    /// An array of descriptive tags for the method.
    var methodTags: [String] = []
    
    /// A description of this method.
    var methodDescription: String?
    
    /// By default, this will match |methodName|.
    var methodOperationId: String
    
    /// The parameters that need to be passed to the method.
    var methodArguments: [SwaggerMethodArgument] = []
    
    /// The HTTP responses that can be generated by the method.
    var methodResponses: [SwaggerResponse] = []
    
    init(name: String)
    {
        self.methodName = name
        self.methodOperationId = name
    }
    
    func generateSwaggerBodyForMethod() -> String?
    {
        return nil
    }
}
