//
//  SwaggerMethod.swift
//  Ernie
//
//  Created by Randy Haid on 12/7/17.
//  Copyright © 2017 Randy Haid. All rights reserved.
//

import Foundation

class SwaggerMethod
{
    enum SwaggerMethodType
    {
        case GET, POST, PUT, DELETE, EVENT
        
        func toString() -> String
        {
            switch self
            {
            case .GET:
                return "get"
            case .POST:
                return "post"
            case .PUT:
                return "put"
            case .DELETE:
                return "delete"
            case .EVENT:
                return "event"
            }
        }
    }
    
    class SwaggerMethodArgument
    {
        var argumentName: String
        var argumentType: SwaggerDataTypeEnum
        var argumentTypeObjectName: String?
        var argumentFormat: SwaggerDataTypeFormatEnum?
        var isArgumentRequired = false
        var argumentDescription: String?
        init(name: String, type: SwaggerDataTypeEnum)
        {
            self.argumentName = name
            self.argumentType = type
        }
        
        func generateSwaggerJson() -> [String : Any]
        {
            var argumentJson: [String : Any] = [:]
            argumentJson["name"] = self.argumentName
            argumentJson["description"] = self.argumentDescription
            argumentJson["in"] = "body"
            argumentJson["schema"] = self.argumentType.generateSwaggerSchemaSection(objectName: nil, arrayType: nil) // TODO
            argumentJson["format"] = self.argumentFormat?.stringValue()
            return argumentJson
        }
    }
    
    class SwaggerResponse
    {
        var responseHttpCode: String
        var responseDataType: SwaggerDataTypeEnum
        var responseDescription: String?
        
        init(code: String, type: SwaggerDataTypeEnum)
        {
            self.responseHttpCode = code
            self.responseDataType = type
        }
        
        func generateSwaggerJson() -> [String : Any]
        {
            var swaggerBody: [String : Any] = [:]
            swaggerBody["schema"] = self.responseDataType.generateSwaggerSchemaSection(objectName: nil, arrayType: nil) // TODO
            if let description = self.responseDescription
            {
                swaggerBody["description"] = description
            }
            return swaggerBody
        }
    }
    
    /// The name of the method.
    var methodName: String
    
    /// Indicates what kind of method this is in the HTTP world.
    var methodType = SwaggerMethodType.GET
    
    /// An array of descriptive tags for the method.
    var methodTags: [String] = []
    
    /// A summary of this method.
    var methodSummary: String?
    
    /// A description of this method.
    var methodDescription: String?
    
    /// By default, this will match |methodName|.
    var methodOperationId: String
    
    /// The parameters that need to be passed to the method.
    var methodArguments: [SwaggerMethodArgument] = []
    
    /// The HTTP responses that can be generated by the method.
    var methodResponses: [SwaggerResponse] = []
    
    /// A list of the type of files that can be accepted/created with this method.
    var methodProducts: [SwaggerProductEnum] = []
    
    init(name: String)
    {
        self.methodName = name
        self.methodOperationId = name
    }
    
    func generateSwaggerSection() -> [String : Any]
    {
        // Create the return object with the simple properties assigned.
        var swaggerBody: [String : Any] = [:]
        swaggerBody["operationId"] = self.methodOperationId
        
        // Add the products to swaggerBody.
        if self.methodProducts.count > 0
        {
            var productStrings: [String] = []
            for product in self.methodProducts
            {
                productStrings.append(product.stringValue())
            }
            swaggerBody["produces"] = productStrings
        }
        else
        {
            swaggerBody["produces"] = [SwaggerProductEnum.JSON.stringValue()]
        }
        
        // Add the tags to swaggerBody.
        if self.methodTags.count > 0
        {
            swaggerBody["tags"] = self.methodTags
        }
        
        // Add the summary to swaggerBody.
        if let summary = self.methodSummary
        {
            swaggerBody["summary"] = summary
        }
        
        // Add the description to swaggerBody.
        if let description = self.methodDescription
        {
            swaggerBody["description"] = description
        }
        
        // Add the parameters to swaggerBody.
        var parametersSection: [[String : Any]] = [[:]]
        for parameter in self.methodArguments
        {
            parametersSection.append(parameter.generateSwaggerJson())
        }
        swaggerBody["parameters"] = parametersSection
        
        // Add the responses to swaggerBody.
        var responsesSection: [String : Any] = [:]
        for response in self.methodResponses
        {
            responsesSection[response.responseHttpCode] = response.generateSwaggerJson()
        }
        swaggerBody["responses"] = responsesSection

        return swaggerBody
    }
}
